"""

Revision ID: 0cf4ac460203
Revises: df712e7b323f
Create Date: 2026-04-17 22:38:24.251665
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0cf4ac460203"
down_revision = "df712e7b323f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts", sa.Column("planned_week_start_date", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "planned_week_start_date")
    # ### end Alembic commands ###
