"""

Revision ID: 18eac510816c
Revises: 39d693e46582
Create Date: 2026-04-03 12:22:56.574204
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '18eac510816c'
down_revision = '39d693e46582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_notion_page_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_training_loads_notion_page_id'), table_name='training_loads')
    op.drop_table('training_loads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_loads',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('min_load', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_load', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('typical_avg_rpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('meaning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notion_page_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('notion_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_loads_pkey')),
    sa.UniqueConstraint('notion_url', name=op.f('training_loads_notion_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_training_loads_notion_page_id'), 'training_loads', ['notion_page_id'], unique=True)
    op.create_table('events',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('target', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('start_date_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('start_date_is_datetime', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('end_date_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date_is_datetime', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('place_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('place_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('place_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('place_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('place_google_place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('race_workout_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notion_page_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('notion_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('events_plan_id_fkey')),
    sa.ForeignKeyConstraint(['race_workout_id'], ['workouts.id'], name=op.f('events_race_workout_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey')),
    sa.UniqueConstraint('notion_url', name=op.f('events_notion_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('plan_id', name=op.f('events_plan_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_events_notion_page_id'), 'events', ['notion_page_id'], unique=True)
    # ### end Alembic commands ###
