"""

Revision ID: 39d693e46582
Revises:
Create Date: 2026-03-15 11:52:33.773675
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39d693e46582"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutrition_guidelines",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("goal", sa.String(length=64), nullable=True),
        sa.Column("applies_to", sa.JSON(), nullable=False),
        sa.Column("carb_strategy", sa.Text(), nullable=True),
        sa.Column("protein_target_g_per_kg", sa.String(length=64), nullable=True),
        sa.Column("fat_target_g_per_kg", sa.String(length=64), nullable=True),
        sa.Column("hydration_electrolytes", sa.Text(), nullable=True),
        sa.Column("supplements", sa.Text(), nullable=True),
        sa.Column("timing_rules", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(
        op.f("ix_nutrition_guidelines_notion_page_id"),
        "nutrition_guidelines",
        ["notion_page_id"],
        unique=True,
    )
    op.create_table(
        "plans",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("plan_goal", sa.Text(), nullable=True),
        sa.Column("constraints", sa.Text(), nullable=True),
        sa.Column("rules_weekly_rhythm", sa.Text(), nullable=True),
        sa.Column("start_date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_date_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("end_date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(op.f("ix_plans_notion_page_id"), "plans", ["notion_page_id"], unique=True)
    op.create_table(
        "training_loads",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("impact", sa.String(length=32), nullable=True),
        sa.Column("min_load", sa.Float(), nullable=True),
        sa.Column("max_load", sa.Float(), nullable=True),
        sa.Column("typical_avg_rpe", sa.Float(), nullable=True),
        sa.Column("meaning", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(
        op.f("ix_training_loads_notion_page_id"), "training_loads", ["notion_page_id"], unique=True
    )
    op.create_table(
        "phases",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("phase_type", sa.String(length=64), nullable=True),
        sa.Column("focus_tags", sa.JSON(), nullable=False),
        sa.Column("weekly_structure", sa.Text(), nullable=True),
        sa.Column("timeframe_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeframe_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeframe_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("nutrition_guideline_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutrition_guideline_id"],
            ["nutrition_guidelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(op.f("ix_phases_notion_page_id"), "phases", ["notion_page_id"], unique=True)
    op.create_table(
        "feedback",
        sa.Column("week", sa.String(length=255), nullable=False),
        sa.Column("energy", sa.Float(), nullable=True),
        sa.Column("leg_freshness", sa.Float(), nullable=True),
        sa.Column("motivation", sa.Float(), nullable=True),
        sa.Column("recovery", sa.Float(), nullable=True),
        sa.Column("biggest_limitation", sa.String(length=64), nullable=True),
        sa.Column("phase_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(op.f("ix_feedback_notion_page_id"), "feedback", ["notion_page_id"], unique=True)
    op.create_table(
        "workouts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("difficulty", sa.String(length=64), nullable=True),
        sa.Column("equipment", sa.JSON(), nullable=False),
        sa.Column("impact", sa.String(length=32), nullable=True),
        sa.Column("metrics_to_record", sa.JSON(), nullable=False),
        sa.Column("purpose", sa.JSON(), nullable=False),
        sa.Column("primarily_used_muscle_group", sa.JSON(), nullable=False),
        sa.Column("planned_distance_km", sa.Float(), nullable=True),
        sa.Column("planned_duration_min", sa.Float(), nullable=True),
        sa.Column("planned_rpe", sa.Float(), nullable=True),
        sa.Column("planned_week_number", sa.Float(), nullable=True),
        sa.Column("actual_rpe", sa.Float(), nullable=True),
        sa.Column("additional_info", sa.String(length=512), nullable=True),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("phase_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["phases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(op.f("ix_workouts_notion_page_id"), "workouts", ["notion_page_id"], unique=True)
    op.create_table(
        "events",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("event_format", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=8), nullable=True),
        sa.Column("start_date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_date_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("end_date_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("place_name", sa.String(length=255), nullable=True),
        sa.Column("place_address", sa.Text(), nullable=True),
        sa.Column("place_latitude", sa.Float(), nullable=True),
        sa.Column("place_longitude", sa.Float(), nullable=True),
        sa.Column("place_google_place_id", sa.String(length=255), nullable=True),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("race_workout_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
        sa.UniqueConstraint("plan_id"),
    )
    op.create_index(op.f("ix_events_notion_page_id"), "events", ["notion_page_id"], unique=True)
    op.create_table(
        "tracked_sessions",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("session_type", sa.String(length=128), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("start_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("end_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_is_datetime", sa.Boolean(), nullable=False),
        sa.Column("active_energy_kj", sa.Float(), nullable=True),
        sa.Column("active_energy_burned_kj", sa.Float(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("calories_kcal", sa.Float(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("duration_min", sa.Float(), nullable=True),
        sa.Column("elevation_ascended_m", sa.Float(), nullable=True),
        sa.Column("elevation_descended_m", sa.Float(), nullable=True),
        sa.Column("intensity_kcal_per_hr_kg", sa.Float(), nullable=True),
        sa.Column("step_cadence_count_per_min", sa.Float(), nullable=True),
        sa.Column("steps", sa.Float(), nullable=True),
        sa.Column("workout_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notion_page_id", sa.String(length=64), nullable=False),
        sa.Column("notion_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notion_url"),
    )
    op.create_index(
        op.f("ix_tracked_sessions_notion_page_id"),
        "tracked_sessions",
        ["notion_page_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_sessions_notion_page_id"), table_name="tracked_sessions")
    op.drop_table("tracked_sessions")
    op.drop_index(op.f("ix_events_notion_page_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_workouts_notion_page_id"), table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_feedback_notion_page_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_phases_notion_page_id"), table_name="phases")
    op.drop_table("phases")
    op.drop_index(op.f("ix_training_loads_notion_page_id"), table_name="training_loads")
    op.drop_table("training_loads")
    op.drop_index(op.f("ix_plans_notion_page_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_nutrition_guidelines_notion_page_id"), table_name="nutrition_guidelines")
    op.drop_table("nutrition_guidelines")
    # ### end Alembic commands ###
