"""

Revision ID: 7baba4b2bbf3
Revises: 8cf9d10deac4
Create Date: 2026-04-11 18:35:03.768679
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7baba4b2bbf3'
down_revision = '8cf9d10deac4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('event_format', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=True),
    sa.Column('start_date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date_is_datetime', sa.Boolean(), nullable=False),
    sa.Column('end_date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date_is_datetime', sa.Boolean(), nullable=False),
    sa.Column('place_name', sa.String(length=255), nullable=True),
    sa.Column('place_address', sa.Text(), nullable=True),
    sa.Column('place_latitude', sa.Float(), nullable=True),
    sa.Column('place_longitude', sa.Float(), nullable=True),
    sa.Column('place_google_place_id', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('race_workout_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=64), nullable=False),
    sa.Column('notion_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['race_workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion_url'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_events_notion_page_id'), 'events', ['notion_page_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_notion_page_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
