"""

Revision ID: 887db4f5c482
Revises: 0cf4ac460203
Create Date: 2026-04-17 22:47:32.426369
"""

from __future__ import annotations

# revision identifiers, used by Alembic.
revision = "887db4f5c482"
down_revision = "0cf4ac460203"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
