"""

Revision ID: e5b74b002400
Revises: 7baba4b2bbf3
Create Date: 2026-04-11 18:35:41.320290
"""

from __future__ import annotations

# revision identifiers, used by Alembic.
revision = "e5b74b002400"
down_revision = "7baba4b2bbf3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
